### PR TITLE
Temporary fix for project switching.

### PR DESCRIPTION
**Pull request by bomgar**
https://github.com/bbatsov/helm-projectile/issues/64
Changes in helm broke this feature. This commit is more of
a workaround to make it work for now.

Actually I have no idea what I'm doing here. But this will fix it until someone comes up with a real solution.

I'm not sure if this should be merged but it would help the users for now.

### CODE REVIEW

**Comment by featalion** [comment]
It works for me, thanks!

**Comment by dmasar** [comment]
this helps me too. thanks!

**Comment by anler** [comment]
works for me as well, thanks!

**Comment by bomgar** [comment]
I close this because https://github.com/bbatsov/helm-projectile/pull/66 actually fixes the problem.

**Pull request closed without merging**
