### PR TITLE
[Fix #94] `helm-projectile-find-file` file creation

### LINKED ISSUE #94: helm-flx-fuzzy-highlighter wrong-type-argument stringp nil
## Expected behavior
helm-projectile opens project

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Error is raised

## Steps to reproduce (recipe)
`helm-projectile-switch-project` then select project

## Backtraces if any (`M-x toggle-debug-on-error`)

capture

## Environment & version information

- `helm-projectile` version: helm-projectile-20180321.324
- `helm` version (in `helm-pkg.el`): 
```elisp
(define-package "helm" "20180321.116" "Helm is an Emacs incremental and narrowing framework"
  '((emacs "24.4")
    (async "1.9.2")
    (popup "0.5.3")
    (helm-core "2.9.0"))
  :url "https://emacs-helm.github.io/helm/")
```
- `projectile` version (`M-x projectile-version`): Projectile 20180317.2220
- Emacs version (`M-x emacs-version`): GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-12
- Spacemacs v.0.300.0 (develop branch commit 0fa3658cd8e283825dcd0a54ce1579dec55eb568)
- OS: Windows 10 v1709 (OS Build 16299.309)

### PR DESCRIPTION
**Pull request by renatofdds**
Add file creation both on current working directory and project root.

### CODE REVIEW

**Comment by xiongtx** [comment]
Seems reasonable. Can you:

1. Rebase on `master`
2. Change the file paths to be relative
  - Path from project dir is sufficient context
  - For deeply nested dirs (*cough* Java *cough*) the path from root could be very long

(2) can be achieved like:

```emacs-lisp
with parent-dir = (file-name-directory (directory-file-name root))
with new-file-on-cwd = (file-relative-name (expand-file-name helm-pattern) parent-dir)
with new-file-on-root = (file-relative-name (expand-file-name helm-pattern root) parent-dir)
```

**Comment by xiongtx** [comment]
I went ahead and implemented this in 71f51e2.

**Comment by renatofdds** [comment]
Thank you very much, unfortunately i haven't had time to look into this in a timely manner. I just got the error, did a quick fix and submitted the PR.

I did it that way (with explicit directory path) in favor of consistent context: 

Since ```projectile-find-file``` list files from ```projectile-project-root``` it suggests that a bare file name on the candidate list is relative to the ```projectile-project-root``` and **not** the actual cwd. Also i believe showing relative path "../../../../" brings no valuable context information (due to many levels of ascending to get to root in most projects). 

Maybe it would be worth considering showing that path only from ```projectile-project-root``` without the filesystem prefix: so we invert the candidates:
- a bare file name (e.g. "issue") which creates the file at project root
- a prefixed path (starting from projectile root down to cwd, e.g. "/path/to/cwd/issue") which creates the file at cwd. 

But ultimately this is opinionated and since you are the maintainer, you get to choose. Thanks again!

**Comment by xiongtx** [comment]
I agree that the semantics are not obvious.  I did it the way it made sense to me, which is what `helm-find-files` does.
 
PR's (and accompanying documentation!) welcome ☺️.

**Pull request closed without merging**
