### PR TITLE
Explicitly write some of the bindings

### PR DESCRIPTION
**Pull request by Malabarba**
Seems that `remap` doesn't work on nested keymaps.

### CODE REVIEW

**Comment by jdreaver** [comment]
`remap` is also not working on `helm-projectile-find-file` for me (`C-c p f`). I have the default config:
* `projectile-find-file` is bound to `C-c p f`
* `helm-projectile-find-file` is bound to `C-c p <remap> <projectile-find-file>`

Thanks for investigating this by the way!

**Comment by Malabarba** [comment]
That one I can't verify. Find-file works fine for me. What do you see if you `C-h v projectile-command-map`?

**Comment by jdreaver** [comment]
Here is the output of `C_h v projectile-command-map`:

```
projectile-command-map is a variable defined in `projectile.el'.
Its value is shown below.

  This variable may be risky if used as a file-local variable.

Documentation:
Keymap for Projectile commands after `projectile-keymap-prefix'.

Value: (keymap
 (remap keymap
        (projectile-ag . helm-projectile-ag)
        (projectile-ack . helm-projectile-ack)
        (projectile-grep . helm-projectile-grep)
        (projectile-switch-to-buffer . helm-projectile-switch-to-buffer)
        (projectile-recentf . helm-projectile-recentf)
        (projectile-switch-project . helm-projectile-switch-project)
        (projectile-find-dir . helm-projectile-find-dir)
        (projectile-find-file-dwim . helm-projectile-find-file-dwim)
        (projectile-find-file-in-known-projects . helm-projectile-find-file-in-known-projects)
        (projectile-find-file . helm-projectile-find-file)
        (projectile-find-other-file . helm-projectile-find-other-file))
 (104 . helm-projectile)
 (27 . projectile-project-buffers-other-buffer)
 (122 . projectile-cache-current-file)
 (120 keymap
      (115 . projectile-run-shell)
      (116 . projectile-run-term)
      (101 . projectile-run-eshell))
 (118 . projectile-vc)
 (117 . projectile-run-project)
 (84 . projectile-find-test-file)
 (116 . projectile-toggle-between-implementation-and-test)
 (83 . projectile-save-project-buffers)
 (115 keymap
      (115 . projectile-ag)
      (103 . projectile-grep))
 (82 . projectile-regenerate-tags)
 (114 . projectile-replace)
 (80 . projectile-test-project)
 (113 . projectile-switch-open-project)
 (112 . projectile-switch-project)
 (111 . projectile-multi-occur)
 (109 . projectile-commander)
 (108 . projectile-find-file-in-directory)
 (107 . projectile-kill-buffers)
 (106 . projectile-find-tag)
 (73 . projectile-ibuffer)
 (105 . projectile-invalidate-cache)
 (70 . projectile-find-file-in-known-projects)
 (103 . projectile-find-file-dwim)
 (102 . projectile-find-file)
 (69 . projectile-edit-dir-locals)
 (101 . projectile-recentf)
 (68 . projectile-dired)
 (100 . projectile-find-dir)
 (99 . projectile-compile-project)
 (98 . projectile-switch-to-buffer)
 (97 . projectile-find-other-file)
 (38 . projectile-run-async-shell-command-in-root)
 (33 . projectile-run-shell-command-in-root)
 (52 keymap
     (116 . projectile-find-implementation-or-test-other-window)
     (103 . projectile-find-file-dwim-other-window)
     (102 . projectile-find-file-other-window)
     (100 . projectile-find-dir-other-window)
     (15 . projectile-display-buffer)
     (98 . projectile-switch-to-buffer-other-window)
     (97 . projectile-find-other-file-other-window)))
```

Interesting, I see the `helm-projectile` stuff in there. I wonder if something else in my config is messing with `remap`. To be honest I had never heard of `remap` until this issue a couple days ago, so forgive my ignorance on this topic haha

**Comment by Malabarba** [comment]
Strange. The keymap looks fine. Do other remaps work for you? Try `projectile-find-dir`.

**Comment by jdreaver** [comment]
Same problem with `projectile-find-dir` and `helm-projectile-find-dir` :/ I asked IRC about `remap` in general, and the only response was some guy telling me that `remap` was evil :smile:

**Comment by Malabarba** [comment]
Maybe it's a new feature. :-/ what's your Emacs version?

**Comment by Malabarba** [comment]
Also, don't take IRC #emacs too seriously. :-) It's a fine place, but a bit prone to over reactions.

**Comment by jdreaver** [comment]
I'm on emacs 24.5.1.

> Also, don't take IRC #emacs too seriously. :-) It's a fine place, but a bit prone to over reactions.

Definitely :)

**Comment by kouhin** [comment]
Emacs devel 25.0.94, remap doesn't work. 
I think it's better to revert #26.

**Comment by lunaryorn** [comment]
@Malabarba @bbatsov Please revert #26; I don't know why, but remaps don't work for me either, and thus all of my Projectile bindings are broken now, including `C-c p p`.

I'm on `25.0.94` if that's relevant.

**Comment by Malabarba** [comment]
Oh well. Guess we should revert then. @bbatsov, could you that?

**Pull request closed without merging**
