### PR TITLE
Remap on projectile-mode-map instead of projectile-command-map

### PR DESCRIPTION
**Pull request by Malabarba**
Hopefully this solves everyone's problems.

### CODE REVIEW

**Comment by kostya-sh** [comment]
This seems to work

**Comment by ali** [comment]
This fix worked for me 👍

**Comment by jdreaver** [comment]
Works for me too, thanks!

**Comment by gtrak** [comment]
I just decided to try helm for the first time today, this was bugging me, and you fixed it :-).

**Pull request merged**
